version: '3'
services:
  mysqldb:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./schema:/docker-entrypoint-initdb.d

    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:latest
    ports:
        - '5432:5432'
    volumes:
        - ./data:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=app
        - POSTGRES_USER=app
        - POSTGRES_PASSWORD=pass

  node:
    build: ./gate-simulator
    image: node:latest
    ports:
      - '9999:9999'


